### ISSUE TITLE
Error on systems with LANG that uses decimal comma

### ISSUE THREAD

**Issue by 6uhrmittag** [Mirdarthos/check_traffic_vnstat#1]
Hi,
thanks for the plugin!

I'm using a DE Ubuntu and got an error:
```
./check_traffic_vnstat -w 100,0 -c 500,0 -W 100,0 -C 500,0 -i ens3
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
(standard_in) 1: syntax error
```

This is because vnstat uses the system LANG for units:
```
# locale (LC_ALL) ("-" = use system locale)
Locale "-"
```
(vi /etc/vnstat.conf)

So, bc gets comma seperated values.

After changing the settings to:
`# locale (LC_ALL) ("-" = use system locale)
Locale "en_us.utf-8"`

It works flawlessly.

This could be solved by replacing `,` with `.` inside the script. But `vnstat.conf` works too.

**Comment by Mirdarthos** [comment]
Thank you. I'll apply it ASAP

**Comment by Mirdarthos** [comment]
Fixed qith @6uhrmittag's commit.
